src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[Vich\Uploadable]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url_video = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;


    #[ORM\Column(length: 255)]
    private ?string $title = null;

    /**
     * @var Collection<int, Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'articles')]
    private Collection $category;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file_video = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    /**
     * @var Collection<int, ArticleImage>
     */
    #[ORM\OneToMany(targetEntity: ArticleImage::class, mappedBy: 'article', cascade: ['persist'], orphanRemoval: true)]
    private Collection $articleImages;

    #[ORM\Column]
    private ?bool $isPublished = false;

    #[ORM\Column]
    private ?bool $isFeatured = false;

    #[ORM\Column(type: 'boolean')]
    private bool $isWelcome = false;



    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->articleImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUrlVideo(): ?string
    {
        return $this->url_video;
    }

    public function setUrlVideo(?string $url_video): static
    {
        $this->url_video = $url_video;

        return $this;
    }


    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }


    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $now = new \DateTimeImmutable();
        $this->created_at = $now;
        $this->updated_at = $now;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getFileVideo(): ?string
    {
        return $this->file_video;
    }

    public function setFileVideo(?string $file_video): static
    {
        $this->file_video = $file_video;

        return $this;
    }


    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, ArticleImage>
     */
    public function getArticleImages(): Collection
    {
        return $this->articleImages;
    }

    public function addArticleImage(ArticleImage $articleImage): static
    {
        if (!$this->articleImages->contains($articleImage)) {
            $this->articleImages->add($articleImage);
            $articleImage->setArticle($this);
        }

        return $this;
    }

    public function removeArticleImage(ArticleImage $articleImage): static
    {
        if ($this->articleImages->removeElement($articleImage)) {
            // set the owning side to null (unless already changed)
            if ($articleImage->getArticle() === $this) {
                $articleImage->setArticle(null);
            }
        }

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function isFeatured(): ?bool
    {
        return $this->isFeatured;
    }

    public function setIsFeatured(bool $isFeatured): static
    {
        $this->isFeatured = $isFeatured;

        return $this;
    }

    public function isWelcome(): bool
    {
        return $this->isWelcome;
    }

    public function setIsWelcome(bool $isWelcome): self
    {
        $this->isWelcome = $isWelcome;
        return $this;
    }
}

src/Controller/ArticleDetailController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class ArticleDetailController extends AbstractController
{
    #[Route('/article/detail/{id<\d+>}', name: 'app_article_detail')]
    public function index(ArticleRepository $articleRepository, int $id): Response
    {
        $article = $articleRepository->find($id);

        if (!$article) {
            throw $this->createNotFoundException('The article does not exist');
        }
        
        return $this->render('article_detail/index.html.twig', [
            'article' => $article,
            'images' => $article->getArticleImages(),
        ]);
    }
}

templates/article_detail/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{ asset('assets/css/article-detail.css') }}">

<main>
    {% include '/_partials/header.html.twig' %}

    <!--Container Article-->
    <div class="container container-article my-4">
        <h1 class="text-center mb-4">{{ article.title }}</h1>


        <!-- Carrousel Images -->
        {% if images is not empty %}
        <div class="carousel-container">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">

                <!-- Indicateurs -->
                <ol class="carousel-indicators">
                    {% for image in images %}
                    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ loop.index0 }}"
                        class="{% if loop.first %}active{% endif %}">
                        <span class="visually-hidden"></span>
                    </li>
                    {% endfor %}
                </ol>

                <!-- Images -->
                <div class="carousel-inner">
                    {% for image in images %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <img src="{{ asset('uploads/images/' ~ image.imagename) }}" class="d-block w-100" alt="Image">
                    </div>
                    {% endfor %}
                </div>

                <!-- Boutons de navigation -->
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>

                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </a>

            </div>
        </div>
        {% endif %}


        <!--Content-->
        <div class="content">
            <p>{{ article.content|nl2br }}</p>
        </div>

        <!--Vidéo-->
        <div class="container-video">
        {% if article.urlVideo %}
        <iframe width="640" height="320" class="col-10 col-md-8 col-lg-6"
            src="https://www.youtube.com/embed/{{ article.urlVideo | split('?v=') | last }}" frameborder="0"
            allowfullscreen>
        </iframe>
        {% elseif article.fileVideo %}
        <video width="560" height="315" controls>
            <source src="{{ asset('uploads/videos/' ~ article.fileVideo) }}" type="video/mp4">
        </video>
        {% endif %}
    </div>

        <!--Auteur et date-->

        <div class="author-date">
            <p>Publié par {{ article.author }} le {{ article.createdAt | date('d/m/Y') }} </p>
            {% if article.updatedAt != article.createdAt %}
            <p>, Modifié le {{ article.updatedAt | date('d/m/Y') }}.</p>
            {% endif %}
        </div>


    </div>

    {% include '/_partials/footer.html.twig' %}
</main>


{% endblock %}